class_words_dict = {
        'Tipo':['fide',
                'frijol',
                'huev',
                'lech',
                'papel',
                'past', 
                'tortill',
                
                       
        ],
        'Tipo_2':[      'alumini',
                        'bay',
                        'blanc',
                        'choriz',
                        'clar',
                        'cod',
                        'codorniz',
                        'condens'
                        'deslact',
                        'encer',
                        'enter',
                        'evapor',
                        'harin',
                        'harin',
                        'hig',
                        'higien',
                        'maiz',
                        'may',
                        'negr',
                        'organ',
                        'peruan',
                        'pint',
                        'salsa/jamon',
                        'semidescrem',
                        'spaguetti',
        
        ],
        'Tipo_3':[      'amarill',
                        'azul',
                        'enchil',
                        'fresc',
                        'light',
                        'nopal',   
                        'oriental',
                        'refrit',
                        'soft',
                        
                       
                       
        ],
        'Tipo_4':[      'jumb',
                        'libre',
                        'enter',
                        'ultra'

        ],
        'Marca':['alpur',
                'blu',
                'carnation',
                'caneloni',
                'chat',
                'cottonell',
                'costen',
                'isador',
                'lal',
                'lecher',
                'lucchetti',
                'mision',
                'orespi',
                'petal',
                'precissim',
                'ranch',
                'regi',
                'reynolds',
                'san',
                'sant',
                'sierr',
                'sorian',
                'verd',
        
        ],
        'Submarca':[    'andres',
                        'beauty',
                        'clar',
                        'dragon', 
                        'juan',
                        'style',
                        'vall',
                        
        ],
        'Empaque':[     'bol',
                        'bols',
                        'bot' 
                        'caj',    
                        'paq',
                        'pouch',
                                               
        ],               
        'Contenido':[   '1',
                        '1/4',
                        '1.5',
                        '1.8',
                        '4',
                        '6'
                        '10',
                        '12',
                        '16',
                        '18',
                        '20',
                        '22',
                        '24',
                        '30',
                        '32',
                        '50',
                        #100 NO
                        '190',
                        '200',
                        '250',
                        '255',
                        '300',
                        '310',
                        '355',
                        '360',
                        '387',
                        '400',
                        '425',
                        '430',
                        '440',
                        '454',
                        '500',
                        '560',
                        '580',
                        '720',
                        '900',
                        '906',
                        '907',
                        '908',
                        #1080 NO
                        #1650 NO

        ],
        'UnidadMedida':['g',
                        'gr',
                        'gram',
                        'kg',
                        'l',
                        'lt',
                        'litr',
                        'pz',
                        'roll',
        ],
}